### ISSUE TITLE
Issues about random shuffle operation and different models

### ISSUE THREAD

**Issue by Arusa1** [jiexiaou/ShuffleFormer#3]
Great works! It is interesting to introducing random shuffle into transformers for breaking the limitation of distance between pixels. However, i am a liitle confused about the following questions after reading the paper:

1. It is effective to calculate similarity after randomly shuffling the pixels? To my opinion, the similarity matrix (the attention map) is highly related to the image content, i.e., the semantic information. After randomly shuffling, the semantic information is totally lost. Thus, the similarity is calculated between two isolated pixels without any contextual information, which I think is somewhat meaningless. Could you please provide more theoretical analysis?

2. The paper provide four different models, i.e., SS, SM, CS, and CM. Particularly, SM means that the shifted window self-attention is adopted for training and the Monte-Carlo averaging is adopted for testing. Why the Monte-Carlo averaging is used for SW-SA (Unlike CW-SA, it could consistently provide the same output for the same input) ?

**Comment by jiexiaou** [comment]
1. Two common priors are considered: non-local and local prior. Non-local prior assumes pixels from an image should be related. Thus, a random subset of pixels grasped from an image can be meaningful for SA. Shuffle exchanges structural information for modeling distance.  Contextual information can be compensated by positional modeling as well as the window self-attention (note we employ alternate window self-attention and CW-SA corresponding with the local and non-local prior.  
2. You can think SS SM CS as ablation study to corresponding to different combinations of the training and testing strategy. SM means training is shifted window but at testing time, shuffle are employed. Its performance is not optimal since the discrepancy of training and testing.
